name: Tests

on:
  push:
    branches:
    - edge
    - feature/*
    paths-ignore:
    - 'LICENSE-*'
    - '**.md'
    - '**.txt'
    - '.github/**'
  pull_request:
    branches:
    - "pull/**"
    paths-ignore:
    - 'LICENSE-*'
    - '**.md'
    - '**.txt'
    - '.github/**'
  workflow_dispatch:

jobs:
  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    - name: Setup Shellcheck & Bats
      run: sudo apt update && sudo apt install bats

    - run: bats -t $( find test/fixture -type f -name "*.bats" )
  style:
    name: Style Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    - name: Initial Setup
      run: sudo apt update && sudo apt install shellcheck

    - run: shellcheck --shell=bash $( find dist setup.sh -type f -name "*.sh" )
